SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `urls` (
`id` int(11) NOT NULL,
  `target` varchar(255) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=123456803 ;


ALTER TABLE `urls`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `target` (`target`);


ALTER TABLE `urls`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=123456803;
